services:
  react_default:
    volumes:
        "paste project volume path here"
    build: .
    image: react:node16
    container_name: react_default
    ports:
        - "3000:3000"
    environment:
        - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm start"
