services:
  
  react_projects:
    volumes:
        "print_docker_compose.sh text is here"
    build: .
    image: react:node16
    container_name: react_projects
    ports:
        - "3000:3000"
        - "3001:3001"
        - "3002:3002"
    environment:
        - CHOKIDAR_USEPOLLING=true
    command: sh -c "tail -f /dev/null"
